#!/usr/bin/python

import json
from pprint import pprint

x = json.loads('{"request": "getwpnam", "name": "raven" }')

if(x.request == 'getwpnam' && x.name == "Yoda" || x.request == 'getwpuid' && x.uid == 100000)
  print '{"name": "Yoda", "passwd": "foobar", "uid":10000, "gid":10000, "gecos": "foobar", "dir": "/home/Yoda", "shell": "/bin/bash"}'
  return 1
else
  return 0

